import '../../bower_components/angular/angular'
import '../../bower_components/angular-translate/angular-translate'
import 'angular-mocks'

import '../js/app'
import '../js/common/common.module'
import '../js/domain/catalog/catalog.module'
import '../js/domain/search/search.module'
import '../js/domain/navigation/navigation.module'

import '../js/common/config/lodash.factory'
import '../js/common/config/i18n.config'

import '../js/domain/navigation/service/menu.service'
import '../js/domain/catalog/service/catalog.service'
import '../js/domain/catalog/service/breadcrumb.service'


// import '../js/common/service/spinner.service'
// import '../js/common/directive/cliplister.directive'
// import '../js/common/directive/httpSrc.directive'
// import '../js/common/directive/jsonld.directive'
// import '../js/common/directive/simple.submenu.directive'
// import '../js/common/filter/image.url.filter'
// // import '../js/common/filter/simplify.characters.filter'
// import '../js/common/controller/content.controller'
// import '../js/common/controller/header.controller'
// import '../js/common/controller/jsonld.controller'

// import '../js/domain/catalog/controller/catalog.controller'
// import '../js/domain/catalog/directive/catalog.template.directive'
// import '../js/domain/catalog/directive/catalog.metadata.directive'
// import '../js/domain/catalog/directive/attribute.value.directive'
// import '../js/domain/catalog/directive/equalize.teaser.height.directive'
// import '../js/domain/catalog/directive/ocs.breadcrumb.directive'
// import '../js/domain/catalog/directive/ocs.data.table.directive'
// import '../js/domain/catalog/directive/ocs.navigate.directive'
// import '../js/domain/catalog/directive/ocs.navigation.menu.directive'
// import '../js/domain/catalog/directive/ocs.new.products.directive'
// import '../js/domain/catalog/directive/switch.language.directive'
